### ISSUE TITLE
pip install without errors, but module import fails.

### ISSUE THREAD

**Issue by awaelchli** [ClementPinard/Pytorch-Correlation-extension#14]
Hi

I tried installing with pip first. this worked without errors, but trying to import the package
`import spatial_correlation_sampler`
gave the error

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/research/envs/pytorch041/lib/python3.7/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/home/adrian/research/envs/pytorch041/lib/python3.7/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /home/adrian/research/envs/pytorch041/lib/python3.7/site-packages/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`

My environment was:
cuda 9.0 
gcc 5.5 
(also tried with cuda9.2/10 and gcc 7.3)
PyTorch 0.4.1 
Python 3.7

### **How I solved it:**
First I cloned the repository and tried with the environment above. This did not work and gave the errors:
`... 
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Correlation_Module/correlation.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status
`

I switched to PyTorch 1.0.1 environment and changed cuda version to 10.0 (and gcc to 7.3) and installed with setup.py again. This finally worked. Not sure why but wanted to share this in case someone else has the same trouble.

@ClementPinard The README says it is expected to compile with 0.4.1, perhaps this info is outdated?

**Comment by ClementPinard** [comment]
Indeed it is. Pytorch 1.0.1 is required.
Sorry about the inconvenience, I'm updating the README !
