### ISSUE TITLE
There was an issue during installation after updating the environment.

### ISSUE THREAD

**Issue by yijiangWang0316** [ClementPinard/Pytorch-Correlation-extension#118]
running install
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\setuptools\_distutils\cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\setuptools\_distutils\cmd.py:90: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing Correlation_Module\spatial_correlation_sampler.egg-info\PKG-INFO
writing dependency_links to Correlation_Module\spatial_correlation_sampler.egg-info\dependency_links.txt
writing requirements to Correlation_Module\spatial_correlation_sampler.egg-info\requires.txt
writing top-level names to Correlation_Module\spatial_correlation_sampler.egg-info\top_level.txt
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\utils\cpp_extension.py:497: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'Correlation_Module\spatial_correlation_sampler.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Correlation_Module\spatial_correlation_sampler.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\utils\cpp_extension.py:382: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\utils\cpp_extension.py:416: UserWarning: The detected CUDA version (12.3) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'spatial_correlation_sampler_backend' extension
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DUSE_CUDA -IC:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\include -IC:\Use
rs\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\include\TH -IC:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\to
rch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include" -IC:\Users\Administrator\Desktop\cellseg\venv\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python312\include -IC:\Users\Administrator\App
Data\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\ATLMFC\include" 
"-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program File
s (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits
\NETFXSDK\4.8\include\um" /EHsc /TpCorrelation_Module\correlation.cpp /Fobuild\temp.win-amd64-cpython-312\Release\Correlation_Module\correlation.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -std=c++17 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
cl: 命令行 warning D9002 :忽略未知选项“-std=c++17”
cl: 命令行 warning D9002 :忽略未知选项“-fopenmp”
correlation.cpp
C:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\nvcc" -c Correlation_Module\correlation_cuda_kernel.cu -o build\temp.win-amd64-cpython-312\Release\Correlation_Module\correlation_cuda_kernel.obj -IC:\Users\Administrator\Desktop
\cellseg\venv\Lib\site-packages\torch\include -IC:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Administrator\Desktop\cellseg\venv\Lib\site-packages\torch\include\TH -IC:\Users\A
dministrator\Desktop\cellseg\venv\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include" -IC:\Users\Administrator\Desktop\cellseg\venv\include -IC:\Users\Administrator\AppData\Local\Programs
\Python\Python312\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include" "-IC:\Program Files\Microsoft Visual Studio\202
2\Community\VC\Tools\MSVC\14.42.34433\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows
 Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.226
21.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_wi
thout_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcomp
iler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 --use-local-env
correlation_cuda_kernel.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\crt/host_config.h(164): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\bin\\nvcc.EXE' failed with exit code 2

==========================================================================================
After updating my torch==2.5.1, torchvision==0.20.1, and torchaudio==2.5.1 (cu121), I encountered a compilation issue. Then, when I reinstalled "spatial_correlation_sampler", I got the error below. What could be the core issue? It was working fine with torch==2.3.1+cu121 before.

I am really looking forward to your reply, as this is very important to me.

**Comment by ClementPinard** [comment]
To avoid the first warning, you can simply do `pip install .` instead of `python setup.py install`

Otherwise, it looks like error is this :

```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\crt/host_config.h(164): fatal error C1189: #error: -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```

So I'm not sure how it works for Windows, but I suppose there's a problem with the compiler chosen. What command di you use exactly ? And what does your environment looks like ?

**Comment by Varun-sai-500** [comment]
@ClementPinard  I am actually working for windows support for this pytorch-correlation-extension, for one of the deep learning projects and I wanted to ask if you're accepting Pull Requests on this repository, I am happy to resolve this issue as this issue is not just about the depreciation of commands but a lot moreabout the windows support

**Comment by ClementPinard** [comment]
Assuming the PR is clear enough, with enough documentation why not. Given how old this issue is, I suppose you want a more general "windows support". Make it clear as referenced as possible so that people not able to test the code on windows (e.g. me) can understand what the PR would change.
